### ISSUE TITLE
CPU Performance issues running shrink-ray instead of compression

### ISSUE THREAD

**Issue by miketoth** [Alorel/shrink-ray#10]
Will give a better repro once we have untangled it from prop software. 

**Env**: Dual-core AWS instance Ubuntu 16.04 instance running a nodev8.9.0, Express 4.x
**Repro** (WIP): Consistently high CPU usage after hitting a route (that returns a large but not unreasonable amount of data) once every 3 seconds. 

Just want to give other users a heads up.

**Comment by Alorel** [comment]
Note that I'm not the author of the library; I just repackaged it with up-to-date dependencies as the original seems to have been abandoned, so I'm not very familiar with the code.

Looking through it, this bit https://github.com/Alorel/shrink-ray/blob/master/index.js#L392 looks like it may be the culprit. Depending on the nature of your data, it may be better to

1. Pre-compress the data (create br/gz versions of the files and send the relevant ones based on the accepts-encoding header)
2. Disable caching for that endpoint.

I'm not very happy with the code in general but unfortunately I haven't had time for programming in a while now.
