### ISSUE TITLE
Abandoned node-zopfli package causes installation failures

### ISSUE THREAD

**Issue by 4cm4k1** [Alorel/shrink-ray#11]
Due to https://github.com/pierreinglebert/node-zopfli apparently being abandoned and consequently https://github.com/pierreinglebert/node-zopfli/issues/87, it is becoming very difficult to install `shrink-ray-current` locally or in production without fatal errors.

I've been able to work around this because my cloud hosting provider has the bindings and the compiled binaries cached; however, this is not a long-term solution.

If, with the community's help, we can identify the outstanding issues with the `node-zopfli` package, I would be willing to create a fork and publish releases via GitHub Releases, so that it stops messing with this package.

Alternatively, I would suggest removing `node-zopfli` from this package to avoid the installation issue. Given that `zopfli` is only useful for static assets, it might not be such a big deal for users to remove.

Thoughts?

**Comment by Alorel** [comment]
I don't know how I feel about removing it. node-zopfli has been causing installation issues starting with Node >=10.0.0 but they can easily be avoided by running `npm/yarn install --build-from-source` to skip downloading prebuilt bindings.

**Comment by 4cm4k1** [comment]
Ah, thanks for that advice, @Alorel! Given the Node v10 note you added in https://github.com/Alorel/shrink-ray/releases/tag/2.1.1, I'm going to close this issue. I wonder if I could somehow make downloading prebuilt bindings work…

**Comment by Alorel** [comment]
The native binding api version was bumped in v10 so unless node-zopfli's author comes back and publishes new prebuilt bindings I'm afraid that won't be possible. :disappointed:
