### ISSUE TITLE
caching function example

### ISSUE THREAD

**Issue by Enalmada** [Alorel/shrink-ray#16]
First off, thank you so much for the time you have put into this keeping it up to date.  

As a very new user to node world, one thing I experienced was wondering how a cache function would actually look:
> If you serve a large number of dynamic files with ETags, you may want to have your cache function restrict caching to your static file directory so as to avoid thrashing the cache and wasting CPU time on expensive compressions.

I think it would be helpful to show an example of that cache function so users could tweak it.  Would it be something like this?  

```
app.use(shrinkRay({cache: shouldCache}));
 
function shouldCache(req, res) {
  if(!req.url.startsWith('/static/') {
      // Don't compress responses that are not static
      return false;
  }
  // fallback to standard cache function
  return shrinkRay.cache(req, res);
}
```

**Comment by Alorel** [comment]
Hey. The readme was copied from the original library and was largely unchanged.

The default cache function is defined as follows so your fallback would not work as `shrinkRay.cache` is undefined:
https://github.com/Alorel/shrink-ray/blob/2eac9a72040554f616f0dbc225e2802a746d896a/index.js#L78

And as for providing examples, I really don't see much of a point:

1. Given how `req` + `res` are standard abbreviations for request + response and how the README uses those variable names, it's clear what data the function can work with.
1. The caching criteria would vary wildly from application to application; we might end up confusing the user even more if they are unable to get past the previous point.

A working version of the example you gave would look like this in its simplest form:

```js
function shouldCache(req) {
   return req.url.startsWith('/static');
}
```

**Comment by Enalmada** [comment]
Part of the confusion was my fault, I was unsure that if I didn't fall back to standard cache function I would cache files without etag or something equivalently bad.  I was afraid my function would override some desired behavior but with your response and a more careful reading of the docs I see that I can return true from my override cache function without fear:
>  shrink-ray ... will never cache a response that does not include an ETag, even if the cache function returns true.

Phew.  Thanks for your help!
