### ISSUE TITLE
RFC8478 (Accept-Encoding: zstd)

### ISSUE THREAD

**Issue by denji** [Alorel/shrink-ray#17]
https://tools.ietf.org/html/rfc8478
https://github.com/tokers/zstd-nginx-module

**Comment by denji** [comment]
https://github.com/tokers/zstd-nginx-module

**Comment by Alorel** [comment]
I'm not sure I get what the issue is.

**Comment by denji** [comment]
You have `deflate`,`gzip`,`brotli`,`zopfli` support but you don't have `zstd` support.

**Comment by Alorel** [comment]
Feel free to make a PR then :+1:
