### ISSUE TITLE
Server push

### ISSUE THREAD

**Issue by rafcontreras** [Alorel/shrink-ray#23]
I want to push a service worker ("/sw.js") when people land on the root ("/") but I don't understand the server-sent events to do this.

I've googled this and can't get this to work

**Comment by Alorel** [comment]
[Sever-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) are different from what [you're looking for](https://en.wikipedia.org/wiki/HTTP/2_Server_Push). SSEs are very similar to web sockets whereas HTTP2 server push is covered in many Express guides.
