### ISSUE TITLE
High severity vulnerability in tar (>=4.4.2) 

### ISSUE THREAD

**Issue by ram-you** [Alorel/shrink-ray#30]
High severity vulnerability in tar (>=4.4.2) ==> (**node-zopfli-es** (1.0.0) > node-gyp > tar (4.4.2)).
https://www.npmjs.com/advisories/803

So please update **node-zopfli-es** to **1.0.1**  ==> ( > node-gyp (3.8.0) > tar (4.4.8))

**Comment by Alorel** [comment]
node-zopfli-es 1.0.1 doesn't solve this. node-gyp is an exact version dependency of node-zopfli-es at v3.8.0. Furthermore, node-gyp is only used when building node-zopfli-es from sources and is not a production security concern.
