### ISSUE TITLE
TypeError: this._implicitHeader is not a function

### ISSUE THREAD

**Issue by lukasoppermann** [Alorel/shrink-ray#55]
Hey, sadly you have the same issue as the express-compress package: https://github.com/expressjs/compression/issues/122 This makes it not work with connect on a normal http2 server. Is there a chance you could change this?

**Comment by fabiwlf** [comment]
If you still need it for http2, you can just extend the express module:

```
import express from "express";
express.response._implicitHeader = function () {
	this.writeHead(this.statusCode);
};
var app = express();
```
